### PR TITLE
Add method to convert double to Decimal

### PR DESCRIPTION
**Pull request by Ashok-Varma**
As this library is trying to replace double operations in dart. 
I think this will be very useful method to interface with other doubles in project.

### CODE REVIEW

**Comment by a14n** [comment]
See #27

**Comment by Ashok-Varma** [comment]
Hi @a14n,

Sorry i missed that

Couple of questions based on #27
1. Is there a chance of (0.1).toString() can be 0.10000000000001 (I thought only when we do operations on doubles the issue arises, is it also with plain double to string ?)
2. Since there will be many interfaces (can be from server, other libraries, ..etc) in an app which can send double. In order to migrate core code to Decimal. This method is a necessity, currently all over the places Decimal.parse(___.toString()) model is used. For now i can get away with extensions though. 

Thanks for the awesome library

**Comment by a14n** [comment]
>Is there a chance of (0.1).toString() can be 0.10000000000001 (I thought only when we do operations on doubles the issue arises, is it also with plain double to string ?)

It's not only for operations on double. For instance `0.12345678901234567890.toString()` outputs `0.12345678901234568`. It would be very confusing that `Decimal.fromDouble(0.12345678901234567890)` doesn't represent `0.1234567890123456789` but `0.12345678901234568`.

>Since there will be many interfaces (can be from server, other libraries, ..etc) in an app which can send double. In order to migrate core code to Decimal.

That's a reason why several currency json API use Strings for value instead of Numbers. See https://stackoverflow.com/questions/29341337/how-to-define-money-amounts-in-an-api

**Comment by Ashok-Varma** [comment]
Hi @a14n 
Thanks for the clarification. It makes sense

**Pull request closed without merging**
