### PR TITLE
fixed Bug with divide to 0

### PR DESCRIPTION
**Pull request by Kuromory**
Maybe give rational a boolean for isUndefined? or change the return type of operator/(Decimal) to Decimal with an exception thrown if divide by 0

### CODE REVIEW

**Comment by a14n** [comment]
Did you face a real bug? `_rational.denominator` is always strictly positive.

**Comment by Kuromory** [comment]
When I did Decimal.parse('1') / Decimal.parse('0) will work BUT when I want to use the toString() I will be in an endless loop because the Deciaml will never be an integer 10 * 0 will still be 0

**Comment by a14n** [comment]
With assertion enabled `Decimal.one / Decimal.zero` throws an exception. You should not be able to make a division by zero. I will add a runtime check to throw even if assertions are disabled. Thanks for your report.

**Comment by a14n** [comment]
The change I mentioned above has been published as part of [rational](https://pub.dev/packages/rational)-2.2.0 . If you upgrade your dependencies you should see an ArgumentError thrown with `Decimal.parse('1') / Decimal.parse('0')`

**Pull request closed without merging**
