### PR TITLE
bumps intl & sdk

### PR DESCRIPTION
**Pull request by jodinathan**

### CODE REVIEW

**Comment by a14n** [comment]
There's an dependency issue. See https://github.com/a14n/dart-decimal/actions/runs/11962390102/job/33375623860?pr=110

**Comment by jodinathan** [comment]
> There's an dependency issue. See https://github.com/a14n/dart-decimal/actions/runs/11962390102/job/33375623860?pr=110

try again please

**Comment by jodinathan** [comment]
the action executed correctly. Is there anything else?

**Comment by a14n** [comment]
I just publish the 3.1.0  version. Thanks for your PR.

**Pull request merged**
